services:
  # Backend API
  - type: web
    name: hospital-blockops-backend
    env: python
    region: oregon
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_DEBUG
        value: False
      - key: CORS_ORIGINS
        value: "*"
      - key: OPENAI_API_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: hospital-blockops-frontend
    env: static
    region: oregon
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://hospital-blockops-backend.onrender.com/api
